# Generated by Django 2.1.4 on 2019-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_power',
            field=models.BooleanField(default=False),
        ),
    ]
